#!/bin/bash
set -e

# https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands
# https://github.com/rossf7/label-schema-automated-build

#https://gist.github.com/DarrenN/8c6a5b969481725a4413
PACKAGE_VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json)
META_VERSION=$(curl https://api.github.com/repos/o2r-project/o2r-meta/commits/master -H "Accept: application/vnd.github.VERSION.sha")

echo "Build hook running for version" $PACKAGE_VERSION
docker build \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VCS_URL=`git config --get remote.origin.url` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=$PACKAGE_VERSION \
  --build-arg META_VERSION=$META_VERSION \
  -t $IMAGE_NAME .
