#!/bin/bash

# https://gist.github.com/DarrenN/8c6a5b969481725a4413
PACKAGE_VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json)
echo Add version tag using $PACKAGE_VERSION

docker tag $IMAGE_NAME $IMAGE_NAME:$PACKAGE_VERSION
